config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :vehicles
  resources :car_shows
  resources :participants
  resources :entries

  root 'car_shows#index'
end

app/models/car_show.rb
class CarShow < ActiveRecord::Base	
	has_many :judges, foreign_key: "uid", class_name: "User"
	has_many :entries

	validates :name, presence: :true
	validates :start, presence: :true
	validates :end, presence: :true

	validate :start_time_is_before_end_time

	validates_associated :entries
	validates_associated :judges
	
	def full_address
		"#{street}, #{city}, #{state} #{zipcode}"
	end

	def start_time_is_before_end_time
		do_boundary_check = true

		if self.start == nil or self.end == nil then
			do_boundary_check = false
		end

		if do_boundary_check then
			if self.start > self.end then
				errors.add(:start, "can't be after the end date")
			end
		end
	end
end

app/controllers/car_shows_controller.rb
class CarShowsController < ApplicationController
  before_action :set_car_show, only: [:show, :edit, :update, :destroy]

  # GET /car_shows
  # GET /car_shows.json
  def index
    @car_shows = CarShow.all
  end

  # GET /car_shows/1
  # GET /car_shows/1.json
  def show
  end

  # GET /car_shows/new
  def new
    @car_show = CarShow.new
  end

  # GET /car_shows/1/edit
  def edit
  end

  # POST /car_shows
  # POST /car_shows.json
  def create
    @car_show = CarShow.new(car_show_params)

    respond_to do |format|
      if @car_show.save
        format.html { redirect_to @car_show, notice: 'Car show was successfully created.' }
        format.json { render :show, status: :created, location: @car_show }
      else
        format.html { render :new }
        format.json { render json: @car_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /car_shows/1
  # PATCH/PUT /car_shows/1.json
  def update
    respond_to do |format|
      if @car_show.update(car_show_params)
        format.html { redirect_to @car_show, notice: 'Car show was successfully updated.' }
        format.json { render :show, status: :ok, location: @car_show }
      else
        format.html { render :edit }
        format.json { render json: @car_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /car_shows/1
  # DELETE /car_shows/1.json
  def destroy
    @car_show.destroy
    respond_to do |format|
      format.html { redirect_to car_shows_url, notice: 'Car show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car_show
      @car_show = CarShow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_show_params
      params.require(:car_show).permit(:start, :end, :name, :street, :city, :state, :zipcode)
    end
end

app/helpers/car_shows_helper.rb
module CarShowsHelper
end

app/views/car_shows/_form.html.erb
<%= simple_form_for(@car_show) do |f| %>
  <% if @car_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car_show.errors.count, "error") %> prohibited this car show from being saved:</h2>

      <ul>
      <% @car_show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <%= f.input :name, icon: "user" %>
    <%= f.input :street %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :zipcode %>
    <%= f.input :start, wrapper_html: { class: 'font-color-mopar-blue'}, as: :datetime_picker %>
    <%= f.input :end, as: :datetime_picker %>

    <div class="col-xs-12">
      <%= f.button :submit, id: 'submit', class: 'btn btn-primary' %>

      <% if !@car_show.new_record? then %>
        <%= link_to 'Back', @car_show, class: 'btn btn-secondary' %>
      <% else %>
        <%= link_to 'Return to List', car_shows_path, class: 'btn btn-secondary' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/car_shows/edit.html.erb
<h1>Editing Car Show</h1>

<%= render 'form' %>

app/views/car_shows/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Car Show', new_car_show_path, class: 'btn btn-secondary btn-sm' %>

<div class="card">
  <div class="card-header">
    <span class="glyphicon glyphicon-dashboard" aria-hidden="true"></span>
    <h4>Car Shows</h4>
  </div>
  <div class="card-block">
    <% @car_shows.each do |car_show| %>
      <% if car_show.valid? %>
      <div class="row">
        <div class="col-xs-12">        
          <h5><%= link_to car_show.name, car_show %></h5>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6">
          <%= car_show.start.to_s(:local_ordinal) %>
        </div>
        <div class="col-xs-6">
          <%= car_show.end.to_s(:local_ordinal) %>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/car_shows/new.html.erb
<h1>New Car Show</h1>

<%= render 'form' %>

app/views/car_shows/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-header">
  	<h4><%= @car_show.name %></h4>
  </div>
  <div class="card-block">    
    <p class="card-text">
    	<strong>Start:</strong> <%= @car_show.start.to_s(:long_ordinal) %> <br />
    	<strong>End:</strong> <%= @car_show.end.to_s(:long_ordinal) %>
    </p>
    <p class="card-text">
    	<div class="col-xs-4">
    		<strong>Entries:</strong> <%= @car_show.entries.count %>
    	</div>
    	<div class="col-xs-8">
    		<%= link_to "New Entry", new_entry_path(car_show: @car_show.id), class: 'btn btn-sm btn-secondary' %>
    	</div>
    </p>

    <div>
	    <%= link_to 'Return to List', car_shows_path, class: 'btn btn-sm btn-secondary' %>
		<%= link_to 'Edit', edit_car_show_path(@car_show), class: 'btn btn-sm btn-secondary' %>
		<%= link_to 'Destroy', @car_show, class: 'btn btn-sm btn-secondary', method: :delete, data: { confirm: 'Are you sure?' } %>
	</div>
  </div>
</div>

<div class="card">
  <div class="card-header">
  	<h4 class="card-title">Location</h4>
  	<small><strong><%= @car_show.full_address %></strong></small>
  </div>
  <div class="card-block" style="height: 240px">    
    <%= render partial: "shared/map", locals: { location: @car_show.full_address } %>
  </div>
</div>