config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :vehicles
  resources :car_shows
  resources :participants
  resources :entries

  root 'car_shows#index'
end

app/models/participant.rb
class Participant < ActiveRecord::Base
	has_many :vehicles	

	def full_name
		return "#{firstName} #{lastName}"
	end	

	def full_address
		return "#{street},#{zipcode}"
	end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params      
      params.require(:participant).permit(:firstName, :lastName, :email, :street, :zipcode)
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <fieldset class="form-group row">
      <div class="form-control-label col-sm-2"><strong>Name</strong></div>
      <div class="col-sm-5">
        <%= f.text_field :firstName, class: "form-control", placeholder: "First name" %>        
      </div>
      <div class="col-sm-5">
        <%= f.text_field :lastName, class: "form-control", placeholder: "Last name" %>
      </div>
    </fieldset>

    <fieldset class="form-group row">
      <%= f.label :email, class: "col-sm-2 form-control-label" %>
      <div class="col-sm-10">
        <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        <small class="text-muted">We'll never share your email with anyone else.</small>
      </div>
    </fieldset>

    <fieldset class="form-group row">
      <%= f.label :street, class: "col-sm-2 form-control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :street, class: "form-control", placeholder: "Street Address" %>
      </div>
    </fieldset>

    <fieldset class="form-group row">
      <%= f.label :zipcode, class: "col-sm-2 form-control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :zipcode, class: "form-control", placeholder: "ZIP Code" %>
      </div>
    </fieldset>

    <fieldset class="form-group row">
      <%= f.submit type: "submit", class: "btn btn-primary" %>
    </fieldset>
  </div>
<% end %>

app/views/participants/_map.html.erb
<div id="mapctl" class="col-xs-12" style="height: 200px"></div>

<%= javascript_tag do %>

function initMap() {
  var map = new google.maps.Map(document.getElementById('mapctl'), {
    zoom: 12
  });
  var geocoder = new google.maps.Geocoder();

  geocodeAddress(geocoder, map);
}

function geocodeAddress(geocoder, resultsMap) {
  var address = '<%=j "#{@participant.full_address}" %>';
  geocoder.geocode({'address': address}, function(results, status) {
    if (status === google.maps.GeocoderStatus.OK) {
      resultsMap.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
        map: resultsMap,
        position: results[0].geometry.location
      });
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });
}

<% end %>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["google_api_key"] %>&callback=initMap" async defer></script>

app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Participants</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
	<div class="card-header">
		<h4><%= @participant.full_name %></h4>
	</div>
	<img class="card-img-top" data-src="...">
	<div class="card-block">
		<p class="card-text">Vechicles: <%= @participant.vehicles.count %></p>
		<p class="card-text">Address: <%= @participant.full_address %></p>
	</div>
</div>

<div class="container row">
	<%= render partial: "shared/map", locals: {location: @participant.full_address} %>
</div>

<div class="container row">
<%= link_to "Edit #{@participant.full_name}", edit_participant_path(@participant), class: "btn btn-secondary btn-sm" %>
<%= link_to 'Participant List', participants_path, class: "btn btn-secondary btn-sm" %>
</div>